// ===== Datos Semilla Oficiales Generados desde CSV =====
import type { AdminStudent, ScheduledLesson } from "./admin-seeds";

export const officialAdminStudents: AdminStudent[] = [
  {
    "id": "as-1",
    "name": "Asaf Chipana Urribarri",
    "family": "Familia Chipana",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "asaf.chipana.urribarri@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Chipana",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-2",
    "name": "Mattew Castillo",
    "family": "Familia Castillo",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "mattew.castillo@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Castillo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-3",
    "name": "Aaron Balarezo Sosa",
    "family": "Familia Balarezo",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "aaron.balarezo.sosa@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Balarezo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-4",
    "name": "Kiara Mariño Huachuilca",
    "family": "Familia Mariño",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "kiara.marino.huachuilca@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Mariño",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-5",
    "name": "Adonis Yared",
    "family": "Familia Yared",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "adonis.yared@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Yared",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-6",
    "name": "Micaela Vilchez Oroncoy",
    "family": "Familia Vilchez",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "micaela.vilchez.oroncoy@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Vilchez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-7",
    "name": "Emmanuel Rospligiosi Gonzales",
    "family": "Familia Rospligiosi",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "emmanuel.rospligiosi.gonzales@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Rospligiosi",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-8",
    "name": "Mishel Suarez Cardenas",
    "family": "Familia Suarez",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Personalizada (S/ 50 por clase)",
    "ageCategory": "JUVENIL",
    "age": 17,
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "mishel.suarez.cardenas@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Suarez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-9",
    "name": "Joan Paolo",
    "family": "Familia Paolo",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Personalizada (S/ 50 por clase)",
    "ageCategory": "ADULTO",
    "age": 24,
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "joan.paolo@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Paolo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-10",
    "name": "Yamir Suarez Salazar",
    "family": "Familia Suarez",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "yamir.suarez.salazar@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Suarez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-11",
    "name": "Layla Mariapaula Florindez Aguilar",
    "family": "Familia Florindez",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "layla.mariapaula.florindez.aguilar@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Florindez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-12",
    "name": "Eithan David Florindez Aguilar",
    "family": "Familia Florindez",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "eithan.david.florindez.aguilar@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Florindez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-13",
    "name": "Ethan Paolo Jara Saldarriaga",
    "family": "Familia Jara",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "ethan.paolo.jara.saldarriaga@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Jara",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-14",
    "name": "Raphaela Yangali",
    "family": "Familia Yangali",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "raphaela.yangali@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Yangali",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-15",
    "name": "Isabella Yangali",
    "family": "Familia Yangali",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "isabella.yangali@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Yangali",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-16",
    "name": "Johandry Sanchez Justa",
    "family": "Familia Sanchez",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "johandry.sanchez.justa@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Sanchez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-17",
    "name": "Francesco Irribarren Paz",
    "family": "Familia Irribarren",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "francesco.irribarren.paz@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Irribarren",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-18",
    "name": "Karen Gutierrez",
    "family": "Familia Gutierrez",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "karen.gutierrez@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Gutierrez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-19",
    "name": "Carolina Luna Tito",
    "family": "Familia Luna",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "carolina.luna.tito@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Luna",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-20",
    "name": "Antonela Diaz Sanchez",
    "family": "Familia Diaz",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "antonela.diaz.sanchez@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Diaz",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-21",
    "name": "Thaisa Oyarce",
    "family": "Familia Oyarce",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "thaisa.oyarce@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Oyarce",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-22",
    "name": "Fabiana Arroyo Tineo",
    "family": "Familia Arroyo",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "fabiana.arroyo.tineo@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Arroyo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-23",
    "name": "Valerie Angulo Chipana",
    "family": "Familia Angulo",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "valerie.angulo.chipana@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Angulo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-24",
    "name": "Francezca Esther Aylas Naupari",
    "family": "Familia Aylas",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "francezca.esther.aylas.naupari@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Aylas",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-25",
    "name": "Leonardo Franco Cabrera",
    "family": "Familia Franco",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "leonardo.franco.cabrera@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Franco",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-26",
    "name": "Andrea Mesa Llallahui",
    "family": "Familia Mesa",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "andrea.mesa.llallahui@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Mesa",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-27",
    "name": "Giuseppe Granda Suarez",
    "family": "Familia Granda",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "giuseppe.granda.suarez@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Granda",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-28",
    "name": "Iker Samán Conislla Huerta",
    "family": "Familia Conislla",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "iker.saman.conislla.huerta@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Conislla",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-29",
    "name": "Ivanna Soto",
    "family": "Familia Soto",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "ivanna.soto@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Soto",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-30",
    "name": "Sara Ximena Ortiz Vivas",
    "family": "Familia Ortiz",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "sara.ximena.ortiz.vivas@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Ortiz",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-31",
    "name": "Marco Antonio Adrian",
    "family": "Familia Adrian",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "marco.antonio.adrian@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Adrian",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-32",
    "name": "Samantha Castillo Rivera",
    "family": "Familia Castillo",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "samantha.castillo.rivera@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Castillo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-33",
    "name": "Camila Pastor Conco",
    "family": "Familia Pastor",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "camila.pastor.conco@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Pastor",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-34",
    "name": "Celeste Elizabeth García Zúñiga",
    "family": "Familia García",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "celeste.elizabeth.garcia.zuniga@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia García",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-35",
    "name": "Sasha Contreras",
    "family": "Familia Contreras",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "sasha.contreras@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Contreras",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-36",
    "name": "Kenny Armando Llallahui Alvarado",
    "family": "Familia Llallahui",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "kenny.armando.llallahui.alvarado@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Llallahui",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-37",
    "name": "Angel Bruno Marcelo",
    "family": "Familia Marcelo",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "angel.bruno.marcelo@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Marcelo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-38",
    "name": "Edward Rios de la Cruz",
    "family": "Familia Rios",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "edward.rios.de.la.cruz@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Rios",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-39",
    "name": "Mirko Malpartida",
    "family": "Familia Malpartida",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Personalizada (S/ 50 por clase)",
    "ageCategory": "JUNIOR",
    "age": 9,
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "mirko.malpartida@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Malpartida",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-40",
    "name": "Santiago Valladolid",
    "family": "Familia Valladolid",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "santiago.valladolid@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Valladolid",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-41",
    "name": "Gabriel Alvarez Galarreta",
    "family": "Familia Alvarez",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "gabriel.alvarez.galarreta@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Alvarez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-42",
    "name": "Boris Axel Marcelo",
    "family": "Familia Marcelo",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "boris.axel.marcelo@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Marcelo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-43",
    "name": "Miranda Aquino",
    "family": "Familia Aquino",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "miranda.aquino@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Aquino",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-44",
    "name": "Mathias Lopez Loayza",
    "family": "Familia Lopez",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "mathias.lopez.loayza@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Lopez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-45",
    "name": "Luis Soto",
    "family": "Familia Soto",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "luis.soto@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Soto",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-46",
    "name": "Luciano Franco Cabrera",
    "family": "Familia Franco",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "luciano.franco.cabrera@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Franco",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-47",
    "name": "Adonis Yeret Tocas Vasquez",
    "family": "Familia Tocas",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "adonis.yeret.tocas.vasquez@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Tocas",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-48",
    "name": "Flavia Concepción Cutisac",
    "family": "Familia Concepción",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "flavia.concepcion.cutisac@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Concepción",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-49",
    "name": "Antonella Osorio Huaman",
    "family": "Familia Osorio",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "antonella.osorio.huaman@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Osorio",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-50",
    "name": "Ethan Romero Manrique",
    "family": "Familia Romero",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "ethan.romero.manrique@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Romero",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-51",
    "name": "Emma Sevilla Perez",
    "family": "Familia Sevilla",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "emma.sevilla.perez@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Sevilla",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-52",
    "name": "Juan Mateo Azael",
    "family": "Familia Azael",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "juan.mateo.azael@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Azael",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-53",
    "name": "Krizia Verástegui Picón",
    "family": "Familia Verástegui",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "krizia.verastegui.picon@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Verástegui",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-54",
    "name": "Geraldine Dulce",
    "family": "Familia Dulce",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "geraldine.dulce@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Dulce",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-55",
    "name": "Dulce",
    "family": "Familia Dulce",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "dulce@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Dulce",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-56",
    "name": "Abigail Zarate",
    "family": "Familia Zarate",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "abigail.zarate@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Zarate",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-57",
    "name": "Thiago Manuel Verástegui Picón",
    "family": "Familia Verástegui",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "thiago.manuel.verastegui.picon@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Verástegui",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-58",
    "name": "Uriel Anton",
    "family": "Familia Anton",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "uriel.anton@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Anton",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-59",
    "name": "Juan Diego Flores Basturen",
    "family": "Familia Flores",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "juan.diego.flores.basturen@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Flores",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-60",
    "name": "Stefan Yrco Samaniego",
    "family": "Familia Yrco",
    "instrument": "Batería",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "stefan.yrco.samaniego@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Yrco",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-61",
    "name": "Eitan Anton Chapi",
    "family": "Familia Anton",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "eitan.anton.chapi@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Anton",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-62",
    "name": "Aithana Rivas Badajoz",
    "family": "Familia Rivas",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "aithana.rivas.badajoz@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Rivas",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-63",
    "name": "Liam Jesús Sánchez Sánchez",
    "family": "Familia Sánchez",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "liam.jesus.sanchez.sanchez@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Sánchez",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-64",
    "name": "Ivanna Soto Soto",
    "family": "Familia Soto",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "ivanna.soto.soto@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Soto",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-65",
    "name": "Niah Jimena Montalvo Huerta",
    "family": "Familia Montalvo",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "niah.jimena.montalvo.huerta@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Montalvo",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-66",
    "name": "Luis Soto Soto",
    "family": "Familia Soto",
    "instrument": "Piano Infantil",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "luis.soto.soto@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Soto",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-67",
    "name": "Junior Gabriel Anton",
    "family": "Familia Anton",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "junior.gabriel.anton@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Anton",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-68",
    "name": "Yajaira Ayquipa Zae",
    "family": "Familia Ayquipa",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "yajaira.ayquipa.zae@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Ayquipa",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-69",
    "name": "Juan Diego Huerta Mitma",
    "family": "Familia Huerta",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "juan.diego.huerta.mitma@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Huerta",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-70",
    "name": "Maryfer Farfan Mendoza",
    "family": "Familia Farfan",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "maryfer.farfan.mendoza@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Farfan",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-71",
    "name": "Marycielo Nicole Farfan Mendoza",
    "family": "Familia Farfan",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "marycielo.nicole.farfan.mendoza@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Farfan",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-72",
    "name": "Abigail Zarate Alcatraz",
    "family": "Familia Zarate",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "abigail.zarate.alcatraz@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Zarate",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-73",
    "name": "Miguel Angel",
    "family": "Familia Angel",
    "instrument": "Piano",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "miguel.angel@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Angel",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-74",
    "name": "Mia Lucero Bellido Alvan",
    "family": "Familia Bellido",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "mia.lucero.bellido.alvan@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Bellido",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-75",
    "name": "Sofía Valentina Conde",
    "family": "Familia Conde",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "sofia.valentina.conde@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Conde",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-76",
    "name": "Joshua Leon Gonzales",
    "family": "Familia Leon",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "joshua.leon.gonzales@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Leon",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-77",
    "name": "Mateo Salvador Malpartida Ramos",
    "family": "Familia Malpartida",
    "instrument": "Guitarra",
    "level": "Nivel 1",
    "teacher": "Jeremy",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "mateo.salvador.malpartida.ramos@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Malpartida",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-78",
    "name": "Carlos Carhuachin Sahuaraura",
    "family": "Familia Carhuachin",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "carlos.carhuachin.sahuaraura@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Carhuachin",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-79",
    "name": "Sofía de la Cruz Vellaneda",
    "family": "Familia de la Cruz",
    "instrument": "Violín",
    "level": "Nivel 1",
    "teacher": "Fernando",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "sofia.de.la.cruz.vellaneda@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia de la Cruz",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  },
  {
    "id": "as-80",
    "name": "Matias Gabriel Quispe Vilcapoma",
    "family": "Familia Quispe",
    "instrument": "Canto",
    "level": "Nivel 1",
    "teacher": "Nathaly",
    "modality": "Regular (8 clases / 45 min)",
    "status": "activo",
    "attendanceRate": 100,
    "payment": "al-dia",
    "risk": 0,
    "joinedAt": "Ago 2026",
    "makeupCredits": 0,
    "balance": 0,
    "recentAttendance": [
      "presente",
      "presente",
      "presente"
    ],
    "teacherNote": "Alumno importado del registro oficial.",
    "email": "matias.gabriel.quispe.vilcapoma@gmail.com",
    "phone": "+51 900 000 000",
    "emergencyContact": {
      "name": "Familia Quispe",
      "phone": "+51 900 000 000",
      "relation": "Apoderado"
    },
    "birthdate": "15 de Agosto"
  }
];

export const officialSchedule: ScheduledLesson[] = [
  {
    "id": "sch-1",
    "day": "Lun",
    "time": "16:00",
    "room": "Sala A",
    "student": "Asaf Chipana Urribarri",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-2",
    "day": "Lun",
    "time": "16:00",
    "room": "Sala B",
    "student": "Mattew Castillo",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-3",
    "day": "Lun",
    "time": "16:00",
    "room": "Sala B",
    "student": "Aaron Balarezo Sosa",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "RECUPERACION",
    "status": "programada"
  },
  {
    "id": "sch-4",
    "day": "Lun",
    "time": "16:00",
    "room": "Sala C",
    "student": "Kiara Mariño Huachuilca",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-5",
    "day": "Lun",
    "time": "16:00",
    "room": "Sala C",
    "student": "Adonis Yared",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-6",
    "day": "Lun",
    "time": "16:45",
    "room": "Sala A",
    "student": "Micaela Vilchez Oroncoy",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-7",
    "day": "Lun",
    "time": "16:45",
    "room": "Sala A",
    "student": "Emmanuel Rospligiosi Gonzales",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-8",
    "day": "Lun",
    "time": "16:45",
    "room": "Sala A",
    "student": "Mishel Suarez Cardenas",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "PERSONALIZADA",
    "weekIndex": 2, // Próxima Semana (Semana 3: 17-22 Agosto)
    "status": "programada"
  },
  {
    "id": "sch-8-w4",
    "day": "Lun",
    "time": "16:45",
    "room": "Sala A",
    "student": "Mishel Suarez Cardenas",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "PERSONALIZADA",
    "weekIndex": 3, // Semana 4: 24-29 Agosto
    "status": "programada"
  },
  {
    "id": "sch-8-piano-lun",
    "day": "Lun",
    "time": "16:45",
    "room": "Sala B",
    "student": "Piano",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-9",
    "day": "Lun",
    "time": "16:45",
    "room": "Sala C",
    "student": "Joan Paolo",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "PERSONALIZADA",
    "status": "programada"
  },
  {
    "id": "sch-10",
    "day": "Lun",
    "time": "17:30",
    "room": "Sala A",
    "student": "Yamir Suarez Salazar",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-11",
    "day": "Lun",
    "time": "17:30",
    "room": "Sala B",
    "student": "Layla Mariapaula Florindez Aguilar",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-12",
    "day": "Lun",
    "time": "17:30",
    "room": "Sala C",
    "student": "Eithan David Florindez Aguilar",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-13",
    "day": "Lun",
    "time": "17:30",
    "room": "Sala C",
    "student": "Ethan Paolo Jara Saldarriaga",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-14",
    "day": "Lun",
    "time": "18:15",
    "room": "Sala A",
    "student": "Johandry Sanchez Justa",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-15",
    "day": "Lun",
    "time": "18:15",
    "room": "Sala B",
    "student": "Francesco Irribarren Paz",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-16",
    "day": "Lun",
    "time": "18:15",
    "room": "Sala C",
    "student": "Karen Gutierrez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "ADULTO",
    "status": "programada"
  },
  {
    "id": "sch-17",
    "day": "Lun",
    "time": "19:00",
    "room": "Sala A",
    "student": "Carolina Luna Tito",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "ADULTO",
    "status": "programada"
  },
  {
    "id": "sch-17-piano-juv",
    "day": "Lun",
    "time": "19:00",
    "room": "Sala B",
    "student": "Piano Juvenil",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-18",
    "day": "Lun",
    "time": "19:00",
    "room": "Sala C",
    "student": "Antonela Diaz Sanchez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-19",
    "day": "Lun",
    "time": "19:00",
    "room": "Sala C",
    "student": "Karen Gutierrez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "RECUPERACION",
    "status": "programada"
  },
  {
    "id": "sch-20",
    "day": "Mar",
    "time": "16:00",
    "room": "Sala B",
    "student": "Valerie Angulo Chipana",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-21",
    "day": "Mar",
    "time": "16:00",
    "room": "Sala B",
    "student": "Aaron Balarezo Sosa",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-22",
    "day": "Mar",
    "time": "16:00",
    "room": "Sala C",
    "student": "Francezca Esther Aylas Naupari",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-23",
    "day": "Mar",
    "time": "16:00",
    "room": "Sala C",
    "student": "Leonardo Franco Cabrera",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-24",
    "day": "Mar",
    "time": "16:00",
    "room": "Sala C",
    "student": "Raphaela Yangali",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-25",
    "day": "Mar",
    "time": "16:00",
    "room": "Sala C",
    "student": "Isabella Yangali",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-26",
    "day": "Mar",
    "time": "16:45",
    "room": "Sala A",
    "student": "Thaisa Oyarce",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-27",
    "day": "Mar",
    "time": "16:45",
    "room": "Sala B",
    "student": "Fabiana Arroyo Tineo",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-28",
    "day": "Mar",
    "time": "16:45",
    "room": "Sala B",
    "student": "Iker Samán Conislla Huerta",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-29",
    "day": "Mar",
    "time": "17:30",
    "room": "Sala A",
    "student": "Sara Ximena Ortiz Vivas",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-30",
    "day": "Mar",
    "time": "17:30",
    "room": "Sala A",
    "student": "Marco Antonio Adrian",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-31",
    "day": "Mar",
    "time": "17:30",
    "room": "Sala B",
    "student": "Samantha Castillo Rivera",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-32",
    "day": "Mar",
    "time": "17:30",
    "room": "Sala B",
    "student": "Camila Pastor Conco",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-33",
    "day": "Mar",
    "time": "17:30",
    "room": "Sala C",
    "student": "Celeste Elizabeth García Zúñiga",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-34",
    "day": "Mar",
    "time": "17:30",
    "room": "Sala C",
    "student": "Sasha Contreras",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-35",
    "day": "Mar",
    "time": "18:15",
    "room": "Sala A",
    "student": "Kenny Armando Llallahui Alvarado",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-36",
    "day": "Mar",
    "time": "18:15",
    "room": "Sala A",
    "student": "Angel Bruno Marcelo",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-37",
    "day": "Mar",
    "time": "18:15",
    "room": "Sala A",
    "student": "Edward Rios de la Cruz",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-38",
    "day": "Mar",
    "time": "18:15",
    "room": "Sala B",
    "student": "Mirko Malpartida",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "PERSONALIZADA",
    "status": "programada"
  },
  {
    "id": "sch-39",
    "day": "Mar",
    "time": "18:15",
    "room": "Sala C",
    "student": "Joan Paolo",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "PERSONALIZADA",
    "status": "programada"
  },
  {
    "id": "sch-40",
    "day": "Mar",
    "time": "19:00",
    "room": "Sala A",
    "student": "Santiago Valladolid",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-41",
    "day": "Mar",
    "time": "19:00",
    "room": "Sala A",
    "student": "Gabriel Alvarez Galarreta",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-42",
    "day": "Mar",
    "time": "19:00",
    "room": "Sala B",
    "student": "Boris Axel Marcelo",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-43",
    "day": "Mar",
    "time": "19:00",
    "room": "Sala B",
    "student": "Miranda Aquino",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-44",
    "day": "Mar",
    "time": "19:00",
    "room": "Sala C",
    "student": "Mathias Lopez Loayza",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-45",
    "day": "Mié",
    "time": "16:00",
    "room": "Sala A",
    "student": "Asaf Chipana Urribarri",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-46",
    "day": "Mié",
    "time": "16:00",
    "room": "Sala A",
    "student": "Thaisa Oyarce",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-47",
    "day": "Mié",
    "time": "16:00",
    "room": "Sala B",
    "student": "Mattew Castillo",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-48",
    "day": "Mié",
    "time": "16:00",
    "room": "Sala C",
    "student": "Kiara Mariño Huachuilca",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-49",
    "day": "Mié",
    "time": "16:00",
    "room": "Sala C",
    "student": "Adonis Yared",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-50",
    "day": "Mié",
    "time": "16:45",
    "room": "Sala A",
    "student": "Micaela Vilchez Oroncoy",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-51",
    "day": "Mié",
    "time": "16:45",
    "room": "Sala A",
    "student": "Emmanuel Rospligiosi Gonzales",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-52",
    "day": "Mié",
    "time": "16:45",
    "room": "Sala A",
    "student": "Mishel Suarez Cardenas",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "PERSONALIZADA",
    "weekIndex": 2, // Próxima Semana (Semana 3: 17-22 Agosto)
    "status": "programada"
  },
  {
    "id": "sch-52-w4",
    "day": "Mié",
    "time": "16:45",
    "room": "Sala A",
    "student": "Mishel Suarez Cardenas",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "PERSONALIZADA",
    "weekIndex": 3, // Semana 4: 24-29 Agosto
    "status": "programada"
  },
  {
    "id": "sch-53",
    "day": "Mié",
    "time": "16:45",
    "room": "Sala B",
    "student": "Fabiana Arroyo Tineo",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "RECUPERACION",
    "status": "programada"
  },
  {
    "id": "sch-54",
    "day": "Mié",
    "time": "16:45",
    "room": "Sala C",
    "student": "Joan Paolo",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "PERSONALIZADA",
    "status": "programada"
  },
  {
    "id": "sch-55",
    "day": "Mié",
    "time": "17:30",
    "room": "Sala A",
    "student": "Yamir Suarez Salazar",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-56",
    "day": "Mié",
    "time": "17:30",
    "room": "Sala B",
    "student": "Layla Mariapaula Florindez Aguilar",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-57",
    "day": "Mié",
    "time": "17:30",
    "room": "Sala C",
    "student": "Eithan David Florindez Aguilar",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-58",
    "day": "Mié",
    "time": "17:30",
    "room": "Sala C",
    "student": "Ethan Paolo Jara Saldarriaga",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-59",
    "day": "Mié",
    "time": "17:30",
    "room": "Sala C",
    "student": "Raphaela Yangali",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-60",
    "day": "Mié",
    "time": "17:30",
    "room": "Sala C",
    "student": "Isabella Yangali",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-61",
    "day": "Mié",
    "time": "18:15",
    "room": "Sala A",
    "student": "Johandry Sanchez Justa",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-62",
    "day": "Mié",
    "time": "18:15",
    "room": "Sala B",
    "student": "Francesco Irribarren Paz",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-63",
    "day": "Mié",
    "time": "19:00",
    "room": "Sala A",
    "student": "Carolina Luna Tito",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "ADULTO",
    "status": "programada"
  },
  {
    "id": "sch-64",
    "day": "Mié",
    "time": "19:00",
    "room": "Sala C",
    "student": "Antonela Diaz Sanchez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-65",
    "day": "Mié",
    "time": "19:00",
    "room": "Sala C",
    "student": "Karen Gutierrez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-66",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala A",
    "student": "Andrea Mesa Llallahui",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-67",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala A",
    "student": "Giuseppe Granda Suarez",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-68",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala B",
    "student": "Valerie Angulo Chipana",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-69",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala B",
    "student": "Aaron Balarezo Sosa",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-70",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala C",
    "student": "Francezca Esther Aylas Naupari",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-71",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala C",
    "student": "Leonardo Franco Cabrera",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-72",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala C",
    "student": "Raphaela Yangali",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-73",
    "day": "Jue",
    "time": "16:00",
    "room": "Sala C",
    "student": "Isabella Yangali",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-74",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala A",
    "student": "Giuseppe Granda Suarez",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-75",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala A",
    "student": "Thaisa Oyarce",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-76",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala B",
    "student": "Fabiana Arroyo Tineo",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-77",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala B",
    "student": "Iker Samán Conislla Huerta",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-78",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala B",
    "student": "Ivanna Soto",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-79",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala C",
    "student": "Luis Soto",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-80",
    "day": "Jue",
    "time": "16:45",
    "room": "Sala C",
    "student": "Luciano Franco Cabrera",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-81",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala A",
    "student": "Sara Ximena Ortiz Vivas",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-82",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala A",
    "student": "Marco Antonio Adrian",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-83",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala A",
    "student": "Angel Bruno Marcelo",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-84",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala B",
    "student": "Camila Pastor Conco",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-85",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala C",
    "student": "Celeste Elizabeth García Zúñiga",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-86",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala C",
    "student": "Sasha Contreras",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-87",
    "day": "Jue",
    "time": "17:30",
    "room": "Sala C",
    "student": "Adonis Yeret Tocas Vasquez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-88",
    "day": "Jue",
    "time": "18:15",
    "room": "Sala A",
    "student": "Kenny Armando Llallahui Alvarado",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-89",
    "day": "Jue",
    "time": "18:15",
    "room": "Sala A",
    "student": "Angel Bruno Marcelo",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-90",
    "day": "Jue",
    "time": "18:15",
    "room": "Sala A",
    "student": "Edward Rios de la Cruz",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-91",
    "day": "Jue",
    "time": "18:15",
    "room": "Sala B",
    "student": "Iker Samán Conislla Huerta",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-92",
    "day": "Jue",
    "time": "18:15",
    "room": "Sala B",
    "student": "Boris Axel Marcelo",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-93",
    "day": "Jue",
    "time": "19:00",
    "room": "Sala A",
    "student": "Gabriel Alvarez Galarreta",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-94",
    "day": "Jue",
    "time": "19:00",
    "room": "Sala A",
    "student": "Santiago Valladolid",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-95",
    "day": "Jue",
    "time": "19:00",
    "room": "Sala B",
    "student": "Boris Axel Marcelo",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-96",
    "day": "Jue",
    "time": "19:00",
    "room": "Sala C",
    "student": "Mathias Lopez Loayza",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-97",
    "day": "Jue",
    "time": "19:00",
    "room": "Sala C",
    "student": "Antonela Diaz Sanchez",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-98",
    "day": "Vie",
    "time": "16:00",
    "room": "Sala B",
    "student": "Flavia Concepción Cutisac",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-99",
    "day": "Vie",
    "time": "16:00",
    "room": "Sala B",
    "student": "Antonella Osorio Huaman",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-100",
    "day": "Vie",
    "time": "16:00",
    "room": "Sala B",
    "student": "Ethan Romero Manrique",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-101",
    "day": "Vie",
    "time": "16:00",
    "room": "Sala B",
    "student": "Emma Sevilla Perez",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-102",
    "day": "Vie",
    "time": "16:00",
    "room": "Sala C",
    "student": "Juan Mateo Azael",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-103",
    "day": "Vie",
    "time": "16:45",
    "room": "Sala A",
    "student": "Ethan Romero Manrique",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-104",
    "day": "Vie",
    "time": "16:45",
    "room": "Sala C",
    "student": "Juan Mateo Azael",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-105",
    "day": "Vie",
    "time": "17:30",
    "room": "Sala A",
    "student": "Krizia Verástegui Picón",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-106",
    "day": "Vie",
    "time": "17:30",
    "room": "Sala B",
    "student": "Geraldine Dulce",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-107",
    "day": "Vie",
    "time": "17:30",
    "room": "Sala C",
    "student": "Dulce",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-108",
    "day": "Vie",
    "time": "18:15",
    "room": "Sala A",
    "student": "Carolina Luna Tito",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "ADULTO",
    "status": "programada"
  },
  {
    "id": "sch-109",
    "day": "Vie",
    "time": "18:15",
    "room": "Sala B",
    "student": "Abigail Zarate",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-110",
    "day": "Vie",
    "time": "19:00",
    "room": "Sala A",
    "student": "Andrea Mesa Llallahui",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-111",
    "day": "Vie",
    "time": "19:00",
    "room": "Sala A",
    "student": "Thiago Manuel Verástegui Picón",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-112",
    "day": "Vie",
    "time": "19:00",
    "room": "Sala B",
    "student": "Samantha Castillo Rivera",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-113",
    "day": "Vie",
    "time": "19:00",
    "room": "Sala B",
    "student": "Camila Pastor Conco",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-114",
    "day": "Vie",
    "time": "19:00",
    "room": "Sala C",
    "student": "Krizia Verástegui Picón",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-115",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala A",
    "student": "Uriel Anton",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-116",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala A",
    "student": "Juan Diego Flores Basturen",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-117",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala A",
    "student": "Stefan Yrco Samaniego",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-118",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala A",
    "student": "Gabriel Alvarez Galarreta",
    "teacher": "Jeremy",
    "instrument": "Batería",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-119",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala B",
    "student": "Eitan Anton Chapi",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-120",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala B",
    "student": "Aithana Rivas Badajoz",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-121",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala B",
    "student": "Liam Jesús Sánchez Sánchez",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-122",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala B",
    "student": "Ivanna Soto Soto",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-123",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala C",
    "student": "Niah Jimena Montalvo Huerta",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-124",
    "day": "Sáb",
    "time": "09:00",
    "room": "Sala C",
    "student": "Luis Soto Soto",
    "teacher": "Nathaly",
    "instrument": "Piano Infantil",
    "category": "INFANTIL",
    "status": "programada"
  },
  {
    "id": "sch-125",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala A",
    "student": "Junior Gabriel Anton",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-126",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala A",
    "student": "Yajaira Ayquipa Zae",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-127",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala A",
    "student": "Juan Diego Huerta Mitma",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-128",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala A",
    "student": "Maryfer Farfan Mendoza",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-129",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala B",
    "student": "Marycielo Nicole Farfan Mendoza",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-130",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala B",
    "student": "Abigail Zarate Alcatraz",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-131",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala B",
    "student": "Miguel Angel",
    "teacher": "Fernando",
    "instrument": "Piano",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-132",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala C",
    "student": "Mia Lucero Bellido Alvan",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-133",
    "day": "Sáb",
    "time": "10:30",
    "room": "Sala C",
    "student": "Sofía Valentina Conde",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUNIOR",
    "status": "programada"
  },
  {
    "id": "sch-134",
    "day": "Sáb",
    "time": "12:00",
    "room": "Sala A",
    "student": "Joshua Leon Gonzales",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-135",
    "day": "Sáb",
    "time": "12:00",
    "room": "Sala A",
    "student": "Mateo Salvador Malpartida Ramos",
    "teacher": "Jeremy",
    "instrument": "Guitarra",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-136",
    "day": "Sáb",
    "time": "12:00",
    "room": "Sala B",
    "student": "Carlos Carhuachin Sahuaraura",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-137",
    "day": "Sáb",
    "time": "12:00",
    "room": "Sala B",
    "student": "Sofía de la Cruz Vellaneda",
    "teacher": "Fernando",
    "instrument": "Violín",
    "category": "JUVENIL",
    "status": "programada"
  },
  {
    "id": "sch-138",
    "day": "Sáb",
    "time": "12:00",
    "room": "Sala C",
    "student": "Matias Gabriel Quispe Vilcapoma",
    "teacher": "Nathaly",
    "instrument": "Canto",
    "category": "JUVENIL",
    "status": "programada"
  }
];
