/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminAlumnosRouteImport } from './routes/admin.alumnos'
import { Route as AdminCampanasRouteImport } from './routes/admin.campanas'
import { Route as AdminControlHorarioRouteImport } from './routes/admin.control-horario'
import { Route as AdminFacturacionRouteImport } from './routes/admin.facturacion'
import { Route as AdminInvitacionesRouteImport } from './routes/admin.invitaciones'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as FamilyIndexRouteImport } from './routes/family.index'
import { Route as FamilyAgendaRouteImport } from './routes/family.agenda'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAgendaRouteImport } from './routes/teacher.agenda'
import { Route as TeacherAlumnosRouteImport } from './routes/teacher.alumnos'
import { Route as TeacherNominaRouteImport } from './routes/teacher.nomina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlumnosRoute = AdminAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanasRoute = AdminCampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlHorarioRoute = AdminControlHorarioRouteImport.update({
  id: '/control-horario',
  path: '/control-horario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturacionRoute = AdminFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitacionesRoute = AdminInvitacionesRouteImport.update({
  id: '/invitaciones',
  path: '/invitaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const FamilyIndexRoute = FamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FamilyRoute,
} as any)
const FamilyAgendaRoute = FamilyAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => FamilyRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAgendaRoute = TeacherAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAlumnosRoute = TeacherAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNominaRoute = TeacherNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/family': typeof FamilyRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alumnos': typeof AdminAlumnosRoute
  '/admin/campanas': typeof AdminCampanasRoute
  '/admin/control-horario': typeof AdminControlHorarioRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/invitaciones': typeof AdminInvitacionesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/family/agenda': typeof FamilyAgendaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/teacher/agenda': typeof TeacherAgendaRoute
  '/teacher/alumnos': typeof TeacherAlumnosRoute
  '/teacher/nomina': typeof TeacherNominaRoute
  '/admin/': typeof AdminIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alumnos': typeof AdminAlumnosRoute
  '/admin/campanas': typeof AdminCampanasRoute
  '/admin/control-horario': typeof AdminControlHorarioRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/invitaciones': typeof AdminInvitacionesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/family/agenda': typeof FamilyAgendaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/teacher/agenda': typeof TeacherAgendaRoute
  '/teacher/alumnos': typeof TeacherAlumnosRoute
  '/teacher/nomina': typeof TeacherNominaRoute
  '/admin': typeof AdminIndexRoute
  '/family': typeof FamilyIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/family': typeof FamilyRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alumnos': typeof AdminAlumnosRoute
  '/admin/campanas': typeof AdminCampanasRoute
  '/admin/control-horario': typeof AdminControlHorarioRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/invitaciones': typeof AdminInvitacionesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/family/agenda': typeof FamilyAgendaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/teacher/agenda': typeof TeacherAgendaRoute
  '/teacher/alumnos': typeof TeacherAlumnosRoute
  '/teacher/nomina': typeof TeacherNominaRoute
  '/admin/': typeof AdminIndexRoute
  '/family/': typeof FamilyIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/family'
    | '/teacher'
    | '/admin/agenda'
    | '/admin/alumnos'
    | '/admin/campanas'
    | '/admin/control-horario'
    | '/admin/facturacion'
    | '/admin/invitaciones'
    | '/admin/whatsapp'
    | '/family/agenda'
    | '/invite/$token'
    | '/teacher/agenda'
    | '/teacher/alumnos'
    | '/teacher/nomina'
    | '/admin/'
    | '/family/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/admin/agenda'
    | '/admin/alumnos'
    | '/admin/campanas'
    | '/admin/control-horario'
    | '/admin/facturacion'
    | '/admin/invitaciones'
    | '/admin/whatsapp'
    | '/family/agenda'
    | '/invite/$token'
    | '/teacher/agenda'
    | '/teacher/alumnos'
    | '/teacher/nomina'
    | '/admin'
    | '/family'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/family'
    | '/teacher'
    | '/admin/agenda'
    | '/admin/alumnos'
    | '/admin/campanas'
    | '/admin/control-horario'
    | '/admin/facturacion'
    | '/admin/invitaciones'
    | '/admin/whatsapp'
    | '/family/agenda'
    | '/invite/$token'
    | '/teacher/agenda'
    | '/teacher/alumnos'
    | '/teacher/nomina'
    | '/admin/'
    | '/family/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  FamilyRoute: typeof FamilyRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alumnos': {
      id: '/admin/alumnos'
      path: '/alumnos'
      fullPath: '/admin/alumnos'
      preLoaderRoute: typeof AdminAlumnosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanas': {
      id: '/admin/campanas'
      path: '/campanas'
      fullPath: '/admin/campanas'
      preLoaderRoute: typeof AdminCampanasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-horario': {
      id: '/admin/control-horario'
      path: '/control-horario'
      fullPath: '/admin/control-horario'
      preLoaderRoute: typeof AdminControlHorarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion': {
      id: '/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AdminFacturacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitaciones': {
      id: '/admin/invitaciones'
      path: '/invitaciones'
      fullPath: '/admin/invitaciones'
      preLoaderRoute: typeof AdminInvitacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/family/': {
      id: '/family/'
      path: '/'
      fullPath: '/family/'
      preLoaderRoute: typeof FamilyIndexRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/family/agenda': {
      id: '/family/agenda'
      path: '/agenda'
      fullPath: '/family/agenda'
      preLoaderRoute: typeof FamilyAgendaRouteImport
      parentRoute: typeof FamilyRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/agenda': {
      id: '/teacher/agenda'
      path: '/agenda'
      fullPath: '/teacher/agenda'
      preLoaderRoute: typeof TeacherAgendaRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/alumnos': {
      id: '/teacher/alumnos'
      path: '/alumnos'
      fullPath: '/teacher/alumnos'
      preLoaderRoute: typeof TeacherAlumnosRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/nomina': {
      id: '/teacher/nomina'
      path: '/nomina'
      fullPath: '/teacher/nomina'
      preLoaderRoute: typeof TeacherNominaRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAlumnosRoute: typeof AdminAlumnosRoute
  AdminCampanasRoute: typeof AdminCampanasRoute
  AdminControlHorarioRoute: typeof AdminControlHorarioRoute
  AdminFacturacionRoute: typeof AdminFacturacionRoute
  AdminInvitacionesRoute: typeof AdminInvitacionesRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAlumnosRoute: AdminAlumnosRoute,
  AdminCampanasRoute: AdminCampanasRoute,
  AdminControlHorarioRoute: AdminControlHorarioRoute,
  AdminFacturacionRoute: AdminFacturacionRoute,
  AdminInvitacionesRoute: AdminInvitacionesRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FamilyRouteChildren {
  FamilyAgendaRoute: typeof FamilyAgendaRoute
  FamilyIndexRoute: typeof FamilyIndexRoute
}

const FamilyRouteChildren: FamilyRouteChildren = {
  FamilyAgendaRoute: FamilyAgendaRoute,
  FamilyIndexRoute: FamilyIndexRoute,
}

const FamilyRouteWithChildren =
  FamilyRoute._addFileChildren(FamilyRouteChildren)

interface TeacherRouteChildren {
  TeacherAgendaRoute: typeof TeacherAgendaRoute
  TeacherAlumnosRoute: typeof TeacherAlumnosRoute
  TeacherNominaRoute: typeof TeacherNominaRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAgendaRoute: TeacherAgendaRoute,
  TeacherAlumnosRoute: TeacherAlumnosRoute,
  TeacherNominaRoute: TeacherNominaRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  FamilyRoute: FamilyRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
